# Generated by Django 2.2.9 on 2020-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
