# Generated by Django 2.2.9 on 2020-01-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200109_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='eventtype',
        ),
    ]
