# Generated by Django 2.2.9 on 2020-01-08 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200109_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact',
            field=models.CharField(default='987654321', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '987654321'. Up to 10 digits allowed.", regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='regnumber',
            field=models.CharField(default='12180222', max_length=8, validators=[django.core.validators.RegexValidator(message="reg number must be entered in the format: '12180222'. Up to 8 digits allowed.", regex='^[0-9]{8}$')]),
        ),
    ]
