# Generated by Django 2.2.9 on 2020-01-08 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200109_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contact',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9876543210'. 10 digits .", regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='regnumber',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator(message="reg number must be entered in the format: '12180222'. Up to 8 digits allowed.", regex='^[0-9]{8}$')]),
        ),
    ]
