# Generated by Django 2.2.9 on 2020-01-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200110_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='contact',
        ),
    ]
