# Generated by Django 2.2.9 on 2020-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_participant_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventid',
            field=models.CharField(default='EW', max_length=20),
        ),
    ]
