# Generated by Django 2.2.9 on 2020-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='slot',
            field=models.IntegerField(choices=[(1, 'SLOT1'), (2, 'SLOT2'), (3, 'SLOT3'), (4, 'SLOT4'), (5, 'SLOT5')], default=1),
        ),
    ]
