# Generated by Django 2.2.9 on 2020-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200111_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accompanying_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_accompanying_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_type',
            field=models.IntegerField(choices=[(0, "Main Participant's"), (1, 'Accompanying Participants')], default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.IntegerField(choices=[(0, 'CE'), (1, 'CS'), (2, 'EC'), (3, 'EEE'), (4, 'IT'), (5, 'ME'), (5, 'MCA'), (7, 'Branch/Dept')], default=7),
        ),
        migrations.AlterField(
            model_name='participant',
            name='slot',
            field=models.IntegerField(choices=[(1, 'SLOT 1'), (2, 'SLOT 2'), (3, 'SLOT 3'), (4, 'SLOT 4'), (5, 'SLOT 5')], default=1),
        ),
    ]
