# Generated by Django 2.2.9 on 2020-01-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200114_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='semester',
            field=models.IntegerField(choices=[(1, 'S2'), (3, 'S4'), (5, 'S6'), (7, 'S8'), (8, 'Semester')]),
        ),
    ]
