# Generated by Django 2.2.9 on 2020-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200114_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Draft'), (2, 'Withdrawn'), (3, 'Finished'), (4, 'Stage 1'), (5, 'Stage 2'), (6, 'Stage 3'), (7, 'Stage 4'), (8, 'Stage 5'), (9, 'Stage 6')], default=1),
        ),
    ]
