# Generated by Django 2.2.9 on 2020-01-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200115_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about',
        ),
        migrations.AddField(
            model_name='event',
            name='stagetype',
            field=models.IntegerField(choices=[(0, 'Onstage'), (1, 'OffStage')], default=0),
        ),
    ]
