# Generated by Django 2.2.9 on 2020-01-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200119_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='substitution',
            field=models.BooleanField(default=False),
        ),
    ]
