# Generated by Django 2.2.9 on 2020-01-22 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20200119_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='regnumber',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator(message="reg number must be entered in the format: '12180222'.Only 8 digits reg numbers are allowed. For MCA S6 :- Please remove first digit (1) and enter remaining ", regex='^[0-9]{8}$')]),
        ),
    ]
